### ISSUE TITLE
bug with power

### ISSUE THREAD

**Issue by vsoch** [neuropower/neuropower#16]
message always says it cannot exceed 1, even when I change it

![image](https://cloud.githubusercontent.com/assets/814322/14583980/1e80c892-03e8-11e6-93f0-95abf6715ef6.png)

**Comment by jokedurnez** [comment]
Power should not exceed 1.

**Comment by vsoch** [comment]
Yeah it was a bug that the field name was a character string, so it was doing the comparison against 1 against a string.
