### ISSUE TITLE
power plot should have option to save

### ISSUE THREAD

**Issue by vsoch** [neuropower/neuropower#24]
It's an svg, so it should be pretty easy to make a button for the user to save it. They might want to use it in a paper!

**Comment by jokedurnez** [comment]
In time I'd like to add a function to save all of it: code + figures + report...  This would then become obsolete, so depends on how much work this is.

**Comment by vsoch** [comment]
That should be doable - could you distinctly define each of those components? (Links to code in the repo would be most helpful!)

**Comment by jokedurnez** [comment]
Hmm.  Right now, the core functions of neuropower are in the utils folder.  Maybe in time it would be best to make this a python library.  The the code to reproduce the whole power analysis would be just a few lines...
Maybe we should chat about the best way to export the whole deal.  Do we need a library or do we define the functions in what is exported?  Do we export just a tarball, or a container or ...?
Imo, this is the next step after the application is fully functioning.

**Comment by jokedurnez** [comment]
(you have all bewitched me with your containers :-) )

**Comment by vsoch** [comment]
I think the goal would be to 1) provide the user with the complete script (function with specified input args) to generate the result, 2) the peak table, and 3) the nice graphics to go along with it, then the simplest thing to do is to zip up those things as a script file, a tab delimited file (table) and a graphic (svg). I had thought neuropower was already modular-ized? If not, it definitely should be. For example, I should be able to do like:

      pip install neuropower
      
Then in python

from neuropower.core import ...

and that kind of thing.

**Comment by jokedurnez** [comment]
Yeeaaaahhhh. No it's not yet modular-ized.  I just define all functions in the utils.  Why would that be urgent?  Will check tomorrow!

**Comment by vsoch** [comment]
Not urgent, just would be good to do to make exporting the reproducible part / code for the user easier :)
