### ISSUE TITLE
user should have option to reset / restart session

### ISSUE THREAD

**Issue by vsoch** [neuropower/neuropower#25]
I'm getting a lot of strange bugs when I go back and try to do things again - may make sense to allow user to restart / reset entire session.

**Comment by jokedurnez** [comment]
The reason why I always read the latest input for a session ID is for when they change stuff to the input.  Reset is a good idea, but these bugs should still get out...

**Comment by vsoch** [comment]
Yes, agreed, but it's nice to have a "reset" button :)
