### ISSUE TITLE
add image of brain as organization picture?

### ISSUE THREAD

**Issue by vsoch** [neuropower/neuropower#32]

**Comment by jokedurnez** [comment]
Could you be more specific?

**Comment by vsoch** [comment]
oh, I meant for the Github organization "Neuropower" right now the image is:

![image](https://cloud.githubusercontent.com/assets/814322/14757917/9313e882-08ad-11e6-91f8-129cdbbe23b3.png)

and it would be cool if it was this one:

![image](https://cloud.githubusercontent.com/assets/814322/14757925/a21e4872-08ad-11e6-8d55-8fd4cea6c531.png)

**Comment by jokedurnez** [comment]
done :)

**Comment by vsoch** [comment]
beautiful!
